// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/applications/perm/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryChannelRelayerRequest is the request type for the Query/ChannelRelayer RPC
// method
type QueryChannelRelayerRequest struct {
	// channel is ibc channel id.
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
}

func (m *QueryChannelRelayerRequest) Reset()         { *m = QueryChannelRelayerRequest{} }
func (m *QueryChannelRelayerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryChannelRelayerRequest) ProtoMessage()    {}
func (*QueryChannelRelayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_835b754d3cf5eb3d, []int{0}
}
func (m *QueryChannelRelayerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryChannelRelayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryChannelRelayerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryChannelRelayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryChannelRelayerRequest.Merge(m, src)
}
func (m *QueryChannelRelayerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryChannelRelayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryChannelRelayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryChannelRelayerRequest proto.InternalMessageInfo

func (m *QueryChannelRelayerRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

// QueryChannelRelayerResponse is the response type for the Query/ChannelRelayer RPC
// method.
type QueryChannelRelayerResponse struct {
	// class_trace returns the requested class id trace information.
	ChannelRelayer *ChannelRelayer `protobuf:"bytes,1,opt,name=channel_relayer,json=channelRelayer,proto3" json:"channel_relayer,omitempty"`
}

func (m *QueryChannelRelayerResponse) Reset()         { *m = QueryChannelRelayerResponse{} }
func (m *QueryChannelRelayerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryChannelRelayerResponse) ProtoMessage()    {}
func (*QueryChannelRelayerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_835b754d3cf5eb3d, []int{1}
}
func (m *QueryChannelRelayerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryChannelRelayerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryChannelRelayerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryChannelRelayerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryChannelRelayerResponse.Merge(m, src)
}
func (m *QueryChannelRelayerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryChannelRelayerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryChannelRelayerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryChannelRelayerResponse proto.InternalMessageInfo

func (m *QueryChannelRelayerResponse) GetChannelRelayer() *ChannelRelayer {
	if m != nil {
		return m.ChannelRelayer
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryChannelRelayerRequest)(nil), "ibc.applications.perm.v1.QueryChannelRelayerRequest")
	proto.RegisterType((*QueryChannelRelayerResponse)(nil), "ibc.applications.perm.v1.QueryChannelRelayerResponse")
}

func init() {
	proto.RegisterFile("ibc/applications/perm/v1/query.proto", fileDescriptor_835b754d3cf5eb3d)
}

var fileDescriptor_835b754d3cf5eb3d = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x1b, 0x41, 0xc5, 0x08, 0x15, 0x16, 0x0f, 0x65, 0x95, 0x45, 0x8a, 0x87, 0xa2, 0x34,
	0xc3, 0xb6, 0xea, 0x03, 0xe8, 0xc5, 0x6b, 0x7b, 0xf4, 0x22, 0x49, 0x08, 0xdb, 0xc0, 0x36, 0x49,
	0x37, 0x69, 0xb1, 0x88, 0x17, 0x9f, 0x40, 0xf0, 0x4d, 0x3c, 0xfb, 0x00, 0x1e, 0x0b, 0x5e, 0x3c,
	0x4a, 0xeb, 0x83, 0xc8, 0x66, 0xb7, 0x68, 0x8b, 0x7b, 0xf0, 0x36, 0x99, 0xf9, 0xe6, 0xff, 0x33,
	0x33, 0xf8, 0x58, 0x32, 0x0e, 0xd4, 0x98, 0x54, 0x72, 0xea, 0xa4, 0x56, 0x16, 0x8c, 0xc8, 0x86,
	0x30, 0x89, 0x61, 0x34, 0x16, 0xd9, 0x94, 0x98, 0x4c, 0x3b, 0x1d, 0x34, 0x24, 0xe3, 0xe4, 0x37,
	0x45, 0x72, 0x8a, 0x4c, 0xe2, 0xf0, 0x84, 0x6b, 0x3b, 0xd4, 0x16, 0x18, 0xb5, 0xa2, 0x68, 0x81,
	0x49, 0xcc, 0x84, 0xa3, 0x31, 0x18, 0x9a, 0x48, 0xe5, 0xf1, 0x42, 0x25, 0xdc, 0x4f, 0x74, 0xa2,
	0x7d, 0x08, 0x79, 0x54, 0x66, 0x0f, 0x13, 0xad, 0x93, 0x54, 0x00, 0x35, 0x12, 0xa8, 0x52, 0xda,
	0x2d, 0x1d, 0x7c, 0xb5, 0xfa, 0x7f, 0x6e, 0x6a, 0x44, 0x49, 0x35, 0x2f, 0x70, 0xd8, 0xcb, 0xbd,
	0xaf, 0x06, 0x54, 0x29, 0x91, 0xf6, 0x45, 0x4a, 0xa7, 0x22, 0xeb, 0x8b, 0xd1, 0x58, 0x58, 0x17,
	0x34, 0xf0, 0x36, 0x2f, 0x0a, 0x0d, 0x74, 0x84, 0x5a, 0x3b, 0xfd, 0xe5, 0xb3, 0x69, 0xf0, 0xc1,
	0x9f, 0x7d, 0xd6, 0x68, 0x65, 0x45, 0xd0, 0xc3, 0x7b, 0x25, 0x79, 0x9b, 0x15, 0x25, 0x2f, 0xb0,
	0xdb, 0x69, 0x91, 0xaa, 0x85, 0x90, 0x35, 0xa9, 0x3a, 0x5f, 0x79, 0x77, 0x5e, 0x11, 0xde, 0xf4,
	0x96, 0xc1, 0x0b, 0xc2, 0xf5, 0x55, 0x38, 0x38, 0xab, 0x96, 0xad, 0x1e, 0x2f, 0x3c, 0xff, 0x67,
	0x57, 0x31, 0x5c, 0xb3, 0xfb, 0xf8, 0xfe, 0xf5, 0xbc, 0xd1, 0x0e, 0x4e, 0xa1, 0x5c, 0xf1, 0xcf,
	0x6a, 0xd7, 0x86, 0x86, 0xfb, 0x32, 0xf1, 0x70, 0x79, 0xfd, 0x36, 0x8f, 0xd0, 0x6c, 0x1e, 0xa1,
	0xcf, 0x79, 0x84, 0x9e, 0x16, 0x51, 0x6d, 0xb6, 0x88, 0x6a, 0x1f, 0x8b, 0xa8, 0x76, 0x43, 0x12,
	0xe9, 0x06, 0x63, 0x46, 0xb8, 0x1e, 0x82, 0x54, 0xd2, 0x49, 0xda, 0x4e, 0x29, 0xb3, 0x65, 0x0c,
	0x77, 0xde, 0xc5, 0x1b, 0xf8, 0xc3, 0xb1, 0x2d, 0x7f, 0xb9, 0xee, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x3f, 0x0f, 0x02, 0x9e, 0x81, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// ChannelRelayer queries a permissioned ibc relayer for the specific channel.
	ChannelRelayer(ctx context.Context, in *QueryChannelRelayerRequest, opts ...grpc.CallOption) (*QueryChannelRelayerResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) ChannelRelayer(ctx context.Context, in *QueryChannelRelayerRequest, opts ...grpc.CallOption) (*QueryChannelRelayerResponse, error) {
	out := new(QueryChannelRelayerResponse)
	err := c.cc.Invoke(ctx, "/ibc.applications.perm.v1.Query/ChannelRelayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// ChannelRelayer queries a permissioned ibc relayer for the specific channel.
	ChannelRelayer(context.Context, *QueryChannelRelayerRequest) (*QueryChannelRelayerResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) ChannelRelayer(ctx context.Context, req *QueryChannelRelayerRequest) (*QueryChannelRelayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChannelRelayer not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_ChannelRelayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryChannelRelayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ChannelRelayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ibc.applications.perm.v1.Query/ChannelRelayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ChannelRelayer(ctx, req.(*QueryChannelRelayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ibc.applications.perm.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChannelRelayer",
			Handler:    _Query_ChannelRelayer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ibc/applications/perm/v1/query.proto",
}

func (m *QueryChannelRelayerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryChannelRelayerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryChannelRelayerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Channel) > 0 {
		i -= len(m.Channel)
		copy(dAtA[i:], m.Channel)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Channel)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryChannelRelayerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryChannelRelayerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryChannelRelayerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ChannelRelayer != nil {
		{
			size, err := m.ChannelRelayer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryChannelRelayerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Channel)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryChannelRelayerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChannelRelayer != nil {
		l = m.ChannelRelayer.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryChannelRelayerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryChannelRelayerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryChannelRelayerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Channel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Channel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryChannelRelayerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryChannelRelayerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryChannelRelayerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelRelayer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ChannelRelayer == nil {
				m.ChannelRelayer = &ChannelRelayer{}
			}
			if err := m.ChannelRelayer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
