// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/applications/perm/v1/types.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PermissionedRelayer is used to specifiy the permissioned relayer for
// the specific port-id:channel-id pair.
type PermissionedRelayer struct {
	PortId    string `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	ChannelId string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Relayer   string `protobuf:"bytes,3,opt,name=relayer,proto3" json:"relayer,omitempty"`
}

func (m *PermissionedRelayer) Reset()         { *m = PermissionedRelayer{} }
func (m *PermissionedRelayer) String() string { return proto.CompactTextString(m) }
func (*PermissionedRelayer) ProtoMessage()    {}
func (*PermissionedRelayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_58b3976370e0fa77, []int{0}
}
func (m *PermissionedRelayer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PermissionedRelayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PermissionedRelayer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PermissionedRelayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionedRelayer.Merge(m, src)
}
func (m *PermissionedRelayer) XXX_Size() int {
	return m.Size()
}
func (m *PermissionedRelayer) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionedRelayer.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionedRelayer proto.InternalMessageInfo

func (m *PermissionedRelayer) GetPortId() string {
	if m != nil {
		return m.PortId
	}
	return ""
}

func (m *PermissionedRelayer) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *PermissionedRelayer) GetRelayer() string {
	if m != nil {
		return m.Relayer
	}
	return ""
}

func init() {
	proto.RegisterType((*PermissionedRelayer)(nil), "ibc.applications.perm.v1.PermissionedRelayer")
}

func init() {
	proto.RegisterFile("ibc/applications/perm/v1/types.proto", fileDescriptor_58b3976370e0fa77)
}

var fileDescriptor_58b3976370e0fa77 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xbd, 0x4a, 0x04, 0x31,
	0x14, 0x85, 0x27, 0x0a, 0xbb, 0x6c, 0xca, 0x58, 0x98, 0xc6, 0x20, 0x62, 0x61, 0x63, 0xc2, 0xe2,
	0x1b, 0x58, 0xb9, 0x9d, 0x6c, 0x69, 0x23, 0xf9, 0x63, 0xf7, 0x42, 0x26, 0x09, 0x49, 0x5c, 0x9c,
	0xb7, 0xf0, 0xb1, 0x2c, 0xa7, 0xb4, 0x94, 0x99, 0x17, 0x91, 0xc4, 0x11, 0xec, 0xee, 0xb9, 0xdf,
	0xe1, 0xc0, 0x87, 0x6f, 0x41, 0x69, 0x21, 0x63, 0x74, 0xa0, 0x65, 0x81, 0xe0, 0xb3, 0x88, 0x36,
	0xf5, 0xe2, 0xb4, 0x15, 0x65, 0x88, 0x36, 0xf3, 0x98, 0x42, 0x09, 0x84, 0x82, 0xd2, 0xfc, 0x7f,
	0x8b, 0xd7, 0x16, 0x3f, 0x6d, 0x6f, 0x0e, 0xf8, 0xe2, 0xd9, 0xa6, 0x1e, 0x72, 0x86, 0xe0, 0xad,
	0xd9, 0x5b, 0x27, 0x07, 0x9b, 0xc8, 0x25, 0x5e, 0xc7, 0x90, 0xca, 0x2b, 0x18, 0x8a, 0xae, 0xd1,
	0xdd, 0x66, 0xbf, 0xaa, 0x71, 0x67, 0xc8, 0x15, 0xc6, 0xfa, 0x28, 0xbd, 0xb7, 0xae, 0xb2, 0xb3,
	0xc6, 0x36, 0xcb, 0x67, 0x67, 0x08, 0xc5, 0xeb, 0xf4, 0x3b, 0x41, 0xcf, 0x1b, 0xfb, 0x8b, 0x8f,
	0x4f, 0x9f, 0x13, 0x43, 0xe3, 0xc4, 0xd0, 0xf7, 0xc4, 0xd0, 0xc7, 0xcc, 0xba, 0x71, 0x66, 0xdd,
	0xd7, 0xcc, 0xba, 0x17, 0x7e, 0x80, 0x72, 0x7c, 0x53, 0x5c, 0x87, 0x5e, 0x80, 0x87, 0x02, 0xf2,
	0xde, 0x49, 0x95, 0x97, 0x5b, 0xbc, 0x8b, 0xaa, 0xd8, 0xac, 0x9a, 0x92, 0x5a, 0x35, 0xa7, 0x87,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x6a, 0xfb, 0x0e, 0xfb, 0x00, 0x00, 0x00,
}

func (m *PermissionedRelayer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PermissionedRelayer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PermissionedRelayer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Relayer) > 0 {
		i -= len(m.Relayer)
		copy(dAtA[i:], m.Relayer)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Relayer)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.PortId) > 0 {
		i -= len(m.PortId)
		copy(dAtA[i:], m.PortId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.PortId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PermissionedRelayer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PortId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Relayer)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PermissionedRelayer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PermissionedRelayer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PermissionedRelayer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PortId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PortId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Relayer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Relayer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
