// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: initia/move/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState - genesis state of x/move
type GenesisState struct {
	Params           Params           `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	ExecutionCounter uint64           `protobuf:"varint,2,opt,name=execution_counter,json=executionCounter,proto3" json:"execution_counter,omitempty" yaml:"execution_counter"`
	Stdlibs          [][]byte         `protobuf:"bytes,3,rep,name=stdlibs,proto3" json:"stdlibs,omitempty"`
	Modules          []Module         `protobuf:"bytes,4,rep,name=modules,proto3" json:"modules,omitempty"`
	Checksums        []Checksum       `protobuf:"bytes,5,rep,name=checksums,proto3" json:"checksums,omitempty"`
	Resources        []Resource       `protobuf:"bytes,6,rep,name=resources,proto3" json:"resources,omitempty"`
	TableInfos       []TableInfo      `protobuf:"bytes,7,rep,name=table_infos,json=tableInfos,proto3" json:"table_infos,omitempty"`
	TableEntries     []TableEntry     `protobuf:"bytes,8,rep,name=table_entries,json=tableEntries,proto3" json:"table_entries,omitempty"`
	DexPairs         []DexPair        `protobuf:"bytes,9,rep,name=dex_pairs,json=dexPairs,proto3" json:"dex_pairs,omitempty"`
	Eip1559Feeparams EIP1559FeeParams `protobuf:"bytes,10,opt,name=eip1559_feeparams,json=eip1559Feeparams,proto3" json:"eip1559_feeparams,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_40442fa21a3f8cef, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetExecutionCounter() uint64 {
	if m != nil {
		return m.ExecutionCounter
	}
	return 0
}

func (m *GenesisState) GetStdlibs() [][]byte {
	if m != nil {
		return m.Stdlibs
	}
	return nil
}

func (m *GenesisState) GetModules() []Module {
	if m != nil {
		return m.Modules
	}
	return nil
}

func (m *GenesisState) GetChecksums() []Checksum {
	if m != nil {
		return m.Checksums
	}
	return nil
}

func (m *GenesisState) GetResources() []Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *GenesisState) GetTableInfos() []TableInfo {
	if m != nil {
		return m.TableInfos
	}
	return nil
}

func (m *GenesisState) GetTableEntries() []TableEntry {
	if m != nil {
		return m.TableEntries
	}
	return nil
}

func (m *GenesisState) GetDexPairs() []DexPair {
	if m != nil {
		return m.DexPairs
	}
	return nil
}

func (m *GenesisState) GetEip1559Feeparams() EIP1559FeeParams {
	if m != nil {
		return m.Eip1559Feeparams
	}
	return EIP1559FeeParams{}
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "initia.move.v1.GenesisState")
}

func init() { proto.RegisterFile("initia/move/v1/genesis.proto", fileDescriptor_40442fa21a3f8cef) }

var fileDescriptor_40442fa21a3f8cef = []byte{
	// 538 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xcf, 0x6e, 0x12, 0x41,
	0x1c, 0xc7, 0x59, 0xa9, 0x50, 0xa6, 0x68, 0xca, 0x6a, 0xed, 0x88, 0xcd, 0xb2, 0x21, 0x1e, 0x48,
	0xa3, 0xbb, 0x41, 0xd3, 0x43, 0x3d, 0x6e, 0xff, 0x18, 0x0e, 0x26, 0x04, 0x8d, 0x31, 0x1e, 0x24,
	0xc3, 0xf2, 0x83, 0x4e, 0x64, 0x77, 0x36, 0x3b, 0xb3, 0x08, 0x6f, 0xe1, 0x63, 0x78, 0xf4, 0x31,
	0x7a, 0xec, 0xd1, 0x13, 0x31, 0x70, 0x30, 0xf1, 0xe8, 0x13, 0x98, 0x9d, 0x1d, 0xa0, 0x1d, 0xb8,
	0x90, 0xc9, 0xfc, 0x3e, 0xdf, 0xcf, 0x77, 0xd8, 0xcc, 0xa0, 0x23, 0x1a, 0x52, 0x41, 0x89, 0x1b,
	0xb0, 0x31, 0xb8, 0xe3, 0xa6, 0x3b, 0x84, 0x10, 0x38, 0xe5, 0x4e, 0x14, 0x33, 0xc1, 0xcc, 0x87,
	0xd9, 0xd4, 0x49, 0xa7, 0xce, 0xb8, 0x59, 0xad, 0x90, 0x80, 0x86, 0xcc, 0x95, 0xbf, 0x19, 0x52,
	0x7d, 0x3c, 0x64, 0x43, 0x26, 0x97, 0x6e, 0xba, 0x52, 0xbb, 0x55, 0x4d, 0x2b, 0xa6, 0x11, 0x28,
	0x69, 0x7d, 0x51, 0x40, 0xe5, 0xb7, 0x59, 0xcd, 0x7b, 0x41, 0x04, 0x98, 0xa7, 0xa8, 0x10, 0x91,
	0x98, 0x04, 0x1c, 0x1b, 0xb6, 0xd1, 0xd8, 0x7b, 0xf5, 0xc4, 0xb9, 0x5b, 0xeb, 0xb4, 0xe5, 0xd4,
	0x2b, 0x5d, 0xcf, 0x6a, 0xb9, 0x1f, 0x7f, 0x7e, 0x1e, 0x1b, 0x1d, 0x15, 0x30, 0x5b, 0xa8, 0x02,
	0x13, 0xf0, 0x13, 0x41, 0x59, 0xd8, 0xf5, 0x59, 0x12, 0x0a, 0x88, 0xf1, 0x3d, 0xdb, 0x68, 0xec,
	0x78, 0x47, 0xff, 0x66, 0x35, 0x3c, 0x25, 0xc1, 0xe8, 0x4d, 0x7d, 0x03, 0xa9, 0x77, 0xf6, 0x57,
	0x7b, 0x67, 0xd9, 0x96, 0xe9, 0xa2, 0x22, 0x17, 0xfd, 0x11, 0xed, 0x71, 0x9c, 0xb7, 0xf3, 0x8d,
	0xb2, 0x77, 0xf0, 0x77, 0x56, 0xab, 0xa8, 0xad, 0x17, 0x2c, 0xa0, 0x02, 0x82, 0x48, 0x4c, 0x3b,
	0x4b, 0xca, 0x6c, 0xa3, 0x62, 0xc0, 0xfa, 0xc9, 0x08, 0x38, 0xde, 0xb1, 0xf3, 0xdb, 0xce, 0xfd,
	0x4e, 0x8e, 0x3d, 0x2b, 0x3d, 0x77, 0x2a, 0x53, 0xf8, 0x5a, 0x96, 0xfd, 0x99, 0xa5, 0xc6, 0xfc,
	0x84, 0x4a, 0xfe, 0x15, 0xf8, 0x5f, 0x79, 0x12, 0x70, 0x7c, 0x5f, 0x3a, 0xb1, 0xee, 0x3c, 0x53,
	0x80, 0x67, 0x2b, 0xeb, 0xa3, 0x55, 0x44, 0xf7, 0xae, 0x65, 0xa9, 0x39, 0x06, 0xce, 0x92, 0xd8,
	0x07, 0x8e, 0x0b, 0xdb, 0xcd, 0x1d, 0x05, 0xac, 0xcd, 0xab, 0xc8, 0x86, 0x79, 0x35, 0x31, 0xbf,
	0xa0, 0x3d, 0x41, 0x7a, 0x23, 0xe8, 0xd2, 0x70, 0xc0, 0x38, 0x2e, 0x4a, 0xf7, 0x53, 0xdd, 0xfd,
	0x21, 0x45, 0x5a, 0xe1, 0x80, 0x79, 0x75, 0x25, 0x3f, 0xb8, 0x95, 0xd2, 0xf5, 0x48, 0x2c, 0x71,
	0x6e, 0x02, 0x7a, 0x90, 0x91, 0x10, 0x8a, 0x98, 0x02, 0xc7, 0xbb, 0xb2, 0xa1, 0xba, 0xb5, 0xe1,
	0x22, 0x14, 0xf1, 0xd4, 0x7b, 0xae, 0x2a, 0x0e, 0xef, 0x04, 0xf5, 0x92, 0xb2, 0x58, 0x26, 0x28,
	0x70, 0xf3, 0x23, 0x2a, 0xf5, 0x61, 0xd2, 0x8d, 0x08, 0x8d, 0x39, 0x2e, 0xc9, 0x8a, 0x43, 0xbd,
	0xe2, 0x1c, 0x26, 0x6d, 0x42, 0xe3, 0xf5, 0xf7, 0x59, 0x25, 0x74, 0xf7, 0x6e, 0x3f, 0x43, 0xb9,
	0xf9, 0x0d, 0x55, 0x80, 0x46, 0xcd, 0x93, 0x93, 0xd3, 0xee, 0x00, 0x40, 0x5d, 0x73, 0x24, 0xaf,
	0xb9, 0xad, 0xfb, 0x2f, 0x5a, 0xed, 0x14, 0xbc, 0x04, 0x50, 0x17, 0xbe, 0xa1, 0x8a, 0x9e, 0x6d,
	0x28, 0xf4, 0xc2, 0x7d, 0x45, 0x5c, 0x2e, 0x01, 0xef, 0xfc, 0x7a, 0x6e, 0x19, 0x37, 0x73, 0xcb,
	0xf8, 0x3d, 0xb7, 0x8c, 0xef, 0x0b, 0x2b, 0x77, 0xb3, 0xb0, 0x72, 0xbf, 0x16, 0x56, 0xee, 0xf3,
	0xf1, 0x90, 0x8a, 0xab, 0xa4, 0xe7, 0xf8, 0x2c, 0x70, 0xb3, 0x13, 0xbc, 0x1c, 0x91, 0x1e, 0x57,
	0x6b, 0x77, 0x92, 0x3d, 0x5a, 0xf9, 0x62, 0x7b, 0x05, 0xf9, 0x64, 0x5f, 0xff, 0x0f, 0x00, 0x00,
	0xff, 0xff, 0x2e, 0x76, 0x2b, 0xad, 0x27, 0x04, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Eip1559Feeparams.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	if len(m.DexPairs) > 0 {
		for iNdEx := len(m.DexPairs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DexPairs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.TableEntries) > 0 {
		for iNdEx := len(m.TableEntries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TableEntries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.TableInfos) > 0 {
		for iNdEx := len(m.TableInfos) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TableInfos[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Resources) > 0 {
		for iNdEx := len(m.Resources) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Resources[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Checksums) > 0 {
		for iNdEx := len(m.Checksums) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Checksums[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Modules) > 0 {
		for iNdEx := len(m.Modules) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Modules[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Stdlibs) > 0 {
		for iNdEx := len(m.Stdlibs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Stdlibs[iNdEx])
			copy(dAtA[i:], m.Stdlibs[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.Stdlibs[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.ExecutionCounter != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ExecutionCounter))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.ExecutionCounter != 0 {
		n += 1 + sovGenesis(uint64(m.ExecutionCounter))
	}
	if len(m.Stdlibs) > 0 {
		for _, b := range m.Stdlibs {
			l = len(b)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Modules) > 0 {
		for _, e := range m.Modules {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Checksums) > 0 {
		for _, e := range m.Checksums {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Resources) > 0 {
		for _, e := range m.Resources {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.TableInfos) > 0 {
		for _, e := range m.TableInfos {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.TableEntries) > 0 {
		for _, e := range m.TableEntries {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.DexPairs) > 0 {
		for _, e := range m.DexPairs {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.Eip1559Feeparams.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutionCounter", wireType)
			}
			m.ExecutionCounter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExecutionCounter |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stdlibs", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Stdlibs = append(m.Stdlibs, make([]byte, postIndex-iNdEx))
			copy(m.Stdlibs[len(m.Stdlibs)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Modules", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Modules = append(m.Modules, Module{})
			if err := m.Modules[len(m.Modules)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Checksums", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Checksums = append(m.Checksums, Checksum{})
			if err := m.Checksums[len(m.Checksums)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Resources", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Resources = append(m.Resources, Resource{})
			if err := m.Resources[len(m.Resources)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TableInfos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TableInfos = append(m.TableInfos, TableInfo{})
			if err := m.TableInfos[len(m.TableInfos)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TableEntries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TableEntries = append(m.TableEntries, TableEntry{})
			if err := m.TableEntries[len(m.TableEntries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DexPairs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DexPairs = append(m.DexPairs, DexPair{})
			if err := m.DexPairs[len(m.DexPairs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Eip1559Feeparams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Eip1559Feeparams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
