// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: initia/tx/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryGasPricesRequest is the request type for the Query/GasPrices RPC method.
type QueryGasPricesRequest struct {
}

func (m *QueryGasPricesRequest) Reset()         { *m = QueryGasPricesRequest{} }
func (m *QueryGasPricesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGasPricesRequest) ProtoMessage()    {}
func (*QueryGasPricesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b8303a398512dd5, []int{0}
}
func (m *QueryGasPricesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGasPricesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGasPricesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGasPricesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGasPricesRequest.Merge(m, src)
}
func (m *QueryGasPricesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGasPricesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGasPricesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGasPricesRequest proto.InternalMessageInfo

// QueryGasPricesResponse is the response type for the Query/GasPrices RPC method.
type QueryGasPricesResponse struct {
	GasPrices github_com_cosmos_cosmos_sdk_types.DecCoins `protobuf:"bytes,1,rep,name=gas_prices,json=gasPrices,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.DecCoins" json:"gas_prices" yaml:"gas_prices"`
}

func (m *QueryGasPricesResponse) Reset()         { *m = QueryGasPricesResponse{} }
func (m *QueryGasPricesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGasPricesResponse) ProtoMessage()    {}
func (*QueryGasPricesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b8303a398512dd5, []int{1}
}
func (m *QueryGasPricesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGasPricesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGasPricesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGasPricesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGasPricesResponse.Merge(m, src)
}
func (m *QueryGasPricesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGasPricesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGasPricesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGasPricesResponse proto.InternalMessageInfo

func (m *QueryGasPricesResponse) GetGasPrices() github_com_cosmos_cosmos_sdk_types.DecCoins {
	if m != nil {
		return m.GasPrices
	}
	return nil
}

// QueryGasPriceRequest is the request type for the Query/GasPrice RPC method.
type QueryGasPriceRequest struct {
	// denom defines the denomination of the gas price to query.
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *QueryGasPriceRequest) Reset()         { *m = QueryGasPriceRequest{} }
func (m *QueryGasPriceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGasPriceRequest) ProtoMessage()    {}
func (*QueryGasPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b8303a398512dd5, []int{2}
}
func (m *QueryGasPriceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGasPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGasPriceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGasPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGasPriceRequest.Merge(m, src)
}
func (m *QueryGasPriceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGasPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGasPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGasPriceRequest proto.InternalMessageInfo

func (m *QueryGasPriceRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// QueryGasPriceResponse is the response type for the Query/GasPrice RPC method.
type QueryGasPriceResponse struct {
	GasPrice github_com_cosmos_cosmos_sdk_types.DecCoin `protobuf:"bytes,1,opt,name=gas_price,json=gasPrice,proto3,casttype=github.com/cosmos/cosmos-sdk/types.DecCoin" json:"gas_price" yaml:"gas_price"`
}

func (m *QueryGasPriceResponse) Reset()         { *m = QueryGasPriceResponse{} }
func (m *QueryGasPriceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGasPriceResponse) ProtoMessage()    {}
func (*QueryGasPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b8303a398512dd5, []int{3}
}
func (m *QueryGasPriceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGasPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGasPriceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGasPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGasPriceResponse.Merge(m, src)
}
func (m *QueryGasPriceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGasPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGasPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGasPriceResponse proto.InternalMessageInfo

func (m *QueryGasPriceResponse) GetGasPrice() github_com_cosmos_cosmos_sdk_types.DecCoin {
	if m != nil {
		return m.GasPrice
	}
	return github_com_cosmos_cosmos_sdk_types.DecCoin{}
}

func init() {
	proto.RegisterType((*QueryGasPricesRequest)(nil), "initia.tx.v1.QueryGasPricesRequest")
	proto.RegisterType((*QueryGasPricesResponse)(nil), "initia.tx.v1.QueryGasPricesResponse")
	proto.RegisterType((*QueryGasPriceRequest)(nil), "initia.tx.v1.QueryGasPriceRequest")
	proto.RegisterType((*QueryGasPriceResponse)(nil), "initia.tx.v1.QueryGasPriceResponse")
}

func init() { proto.RegisterFile("initia/tx/v1/query.proto", fileDescriptor_8b8303a398512dd5) }

var fileDescriptor_8b8303a398512dd5 = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xbd, 0x6f, 0xd3, 0x40,
	0x14, 0xcf, 0x15, 0x15, 0x35, 0x07, 0x03, 0x9c, 0x02, 0x58, 0x56, 0x65, 0x5b, 0x57, 0x86, 0xf0,
	0xd1, 0x3b, 0xb9, 0x6c, 0x8c, 0x2d, 0x02, 0x46, 0xf0, 0xc8, 0x82, 0xce, 0xee, 0xc9, 0x9c, 0x88,
	0xef, 0xdc, 0xdc, 0xc5, 0x4a, 0x84, 0x2a, 0x01, 0x12, 0x3b, 0x12, 0x23, 0x0b, 0x33, 0x7f, 0x49,
	0xc7, 0x4a, 0x2c, 0x4c, 0x01, 0x25, 0xfc, 0x05, 0x8c, 0x4c, 0xc8, 0x77, 0x76, 0xda, 0x44, 0x10,
	0x98, 0x7c, 0x7e, 0x1f, 0xbf, 0x8f, 0xf7, 0x1e, 0xf4, 0x84, 0x14, 0x46, 0x30, 0x6a, 0xc6, 0xb4,
	0x8a, 0xe9, 0xd1, 0x88, 0x0f, 0x27, 0xa4, 0x1c, 0x2a, 0xa3, 0xd0, 0x65, 0x97, 0x21, 0x66, 0x4c,
	0xaa, 0xd8, 0x0f, 0x32, 0xa5, 0x0b, 0xa5, 0x69, 0xca, 0x34, 0xa7, 0x55, 0x9c, 0x72, 0xc3, 0x62,
	0x9a, 0x29, 0x21, 0x5d, 0xb5, 0xdf, 0xcb, 0x55, 0xae, 0xec, 0x93, 0xd6, 0xaf, 0x26, 0xba, 0x9d,
	0x2b, 0x95, 0x0f, 0x38, 0x65, 0xa5, 0xa0, 0x4c, 0x4a, 0x65, 0x98, 0x11, 0x4a, 0x6a, 0x97, 0xc5,
	0x37, 0xe0, 0xb5, 0xa7, 0x35, 0xe1, 0x23, 0xa6, 0x9f, 0x0c, 0x45, 0xc6, 0x75, 0xc2, 0x8f, 0x46,
	0x5c, 0x1b, 0xfc, 0x09, 0xc0, 0xeb, 0xab, 0x19, 0x5d, 0x2a, 0xa9, 0x39, 0x7a, 0x07, 0x20, 0xcc,
	0x99, 0x7e, 0x5e, 0xda, 0xb0, 0x07, 0xa2, 0x0b, 0xfd, 0x4b, 0x7b, 0xdb, 0xc4, 0xa9, 0x23, 0xb5,
	0x3a, 0xd2, 0xa8, 0x23, 0x0f, 0x78, 0x76, 0xa0, 0x84, 0xdc, 0x7f, 0x7c, 0x32, 0x0d, 0x3b, 0x3f,
	0xa7, 0xe1, 0xd5, 0x09, 0x2b, 0x06, 0xf7, 0xf1, 0x59, 0x37, 0xfe, 0xfc, 0x2d, 0xbc, 0x93, 0x0b,
	0xf3, 0x62, 0x94, 0x92, 0x4c, 0x15, 0xb4, 0xb1, 0xe8, 0x3e, 0xbb, 0xfa, 0xf0, 0x25, 0x35, 0x93,
	0x92, 0xeb, 0x16, 0x48, 0x27, 0xdd, 0xbc, 0xd5, 0x83, 0xef, 0xc2, 0xde, 0x92, 0xc2, 0x46, 0x3a,
	0xea, 0xc1, 0xcd, 0x43, 0x2e, 0x55, 0xe1, 0x81, 0x08, 0xf4, 0xbb, 0x89, 0xfb, 0xc1, 0x1f, 0xc1,
	0x8a, 0xd5, 0x85, 0x9f, 0x37, 0x00, 0x76, 0x17, 0x8a, 0x6c, 0xd3, 0xbf, 0xec, 0x3c, 0x6c, 0xec,
	0x5c, 0x59, 0xb1, 0x83, 0x7f, 0x4d, 0xc3, 0xdb, 0xff, 0xef, 0x26, 0xd9, 0x6a, 0xcd, 0xec, 0xbd,
	0xde, 0x80, 0x9b, 0x56, 0x1d, 0x1a, 0xc3, 0xee, 0x62, 0xe4, 0x68, 0x87, 0x9c, 0xbf, 0x00, 0xf2,
	0xc7, 0x55, 0xf9, 0x37, 0xd7, 0x17, 0x39, 0x97, 0x38, 0x7a, 0xfb, 0xe5, 0xc7, 0x87, 0x0d, 0x1f,
	0x79, 0x74, 0xe9, 0xdc, 0xce, 0x56, 0x81, 0x8e, 0xe1, 0x56, 0xdb, 0x86, 0xf0, 0x1a, 0xcc, 0x96,
	0x77, 0x67, 0x6d, 0x4d, 0x43, 0xdb, 0xb7, 0xb4, 0x18, 0x45, 0x7f, 0xa3, 0xa5, 0xaf, 0xec, 0x7e,
	0x8e, 0xf7, 0x0f, 0x4e, 0x66, 0x01, 0x38, 0x9d, 0x05, 0xe0, 0xfb, 0x2c, 0x00, 0xef, 0xe7, 0x41,
	0xe7, 0x74, 0x1e, 0x74, 0xbe, 0xce, 0x83, 0xce, 0xb3, 0x5b, 0xe7, 0x46, 0xea, 0x50, 0x76, 0x07,
	0x2c, 0xd5, 0x2d, 0x62, 0x15, 0xd7, 0xa0, 0x76, 0xb2, 0xe9, 0x45, 0x7b, 0xd6, 0xf7, 0x7e, 0x07,
	0x00, 0x00, 0xff, 0xff, 0x8e, 0x8d, 0x1f, 0xbb, 0x54, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// GasPrices returns the gas prices for the network.
	GasPrices(ctx context.Context, in *QueryGasPricesRequest, opts ...grpc.CallOption) (*QueryGasPricesResponse, error)
	// GasPrice returns the gas price for the network.
	GasPrice(ctx context.Context, in *QueryGasPriceRequest, opts ...grpc.CallOption) (*QueryGasPriceResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GasPrices(ctx context.Context, in *QueryGasPricesRequest, opts ...grpc.CallOption) (*QueryGasPricesResponse, error) {
	out := new(QueryGasPricesResponse)
	err := c.cc.Invoke(ctx, "/initia.tx.v1.Query/GasPrices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GasPrice(ctx context.Context, in *QueryGasPriceRequest, opts ...grpc.CallOption) (*QueryGasPriceResponse, error) {
	out := new(QueryGasPriceResponse)
	err := c.cc.Invoke(ctx, "/initia.tx.v1.Query/GasPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// GasPrices returns the gas prices for the network.
	GasPrices(context.Context, *QueryGasPricesRequest) (*QueryGasPricesResponse, error)
	// GasPrice returns the gas price for the network.
	GasPrice(context.Context, *QueryGasPriceRequest) (*QueryGasPriceResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GasPrices(ctx context.Context, req *QueryGasPricesRequest) (*QueryGasPricesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GasPrices not implemented")
}
func (*UnimplementedQueryServer) GasPrice(ctx context.Context, req *QueryGasPriceRequest) (*QueryGasPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GasPrice not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GasPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGasPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GasPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/initia.tx.v1.Query/GasPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GasPrices(ctx, req.(*QueryGasPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GasPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGasPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GasPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/initia.tx.v1.Query/GasPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GasPrice(ctx, req.(*QueryGasPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "initia.tx.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GasPrices",
			Handler:    _Query_GasPrices_Handler,
		},
		{
			MethodName: "GasPrice",
			Handler:    _Query_GasPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "initia/tx/v1/query.proto",
}

func (m *QueryGasPricesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGasPricesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGasPricesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGasPricesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGasPricesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGasPricesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GasPrices) > 0 {
		for iNdEx := len(m.GasPrices) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GasPrices[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGasPriceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGasPriceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGasPriceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGasPriceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGasPriceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGasPriceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.GasPrice.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGasPricesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGasPricesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.GasPrices) > 0 {
		for _, e := range m.GasPrices {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryGasPriceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGasPriceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.GasPrice.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGasPricesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGasPricesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGasPricesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGasPricesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGasPricesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGasPricesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasPrices", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GasPrices = append(m.GasPrices, types.DecCoin{})
			if err := m.GasPrices[len(m.GasPrices)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGasPriceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGasPriceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGasPriceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGasPriceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGasPriceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGasPriceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasPrice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GasPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
